# The  older where your airflow pipelines live, most likely a
repos:
-   repo: https://github.com/psf/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.7
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
    - id: flake8
      additional_dependencies: [flake8-typing-imports==1.6.0]
      args: [--max-line-length=120]
